#!/bin/bash

function redmine_set_status
{
    /usr/local/share/Weborama-Git-Review/helpers/redmine-set-status-id --id="$1" --status_id="$2" --auth_key="$REDMINE_AUTHKEY" --server_url="$REDMINE_URL" 2> /dev/null
    if [ $? -ne 0 ]
    then
        echo "Can't change the redmine status of task $1 with value $2 ..."
        exit 1
    fi
}

