#!/bin/bash

cd "$(readlink -f "$(dirname "$(git rev-parse --git-dir)")")"

REDMINE_AUTHKEY=$(git config redmine.authkey)
REDMINE_URL=$(git config redmine.url)

REDMINE_REVIEW_TODO=$(git config redmine.statuses.review.assigned)
REDMINE_REVIEW_IN_PROGRESS=$(git config redmine.statuses.review.inprogress)
REDMINE_REVIEW_FINISH=$(git config redmine.statuses.review.finish)

REDMINE_USER_ID=$(git config redmine.user.id)

REDMINE_TASK_TODO=$(git config redmine.statuses.task.assigned)
REDMINE_TASK_IN_PROGRESS=$(git config redmine.statuses.task.inprogress)

function redmine_help
{
    cat <<__EOF__
Please configure your redmine instance :
    git config --global --add redmine.authkey YOUR_AUTH_KEY
    git config --global --add redmine.url THE_REDMINE_URL_SERVER

__EOF__
}

function redmine_help_with_statuses
{
    cat <<__EOF__
Please configure your redmine instance :
    git config --global --add redmine.statuses.review.assigned ID
    git config --global --add redmine.statuses.review.inprogress ID
    git config --global --add redmine.statuses.review.finish ID
    git config --global --add redmine.statuses.task.assigned ID
    git config --global --add redmine.statuses.task.inprogress ID

__EOF__
    /usr/local/share/Weborama-Git-Review/helpers/redmine-get-statuses-ids --auth_key="$REDMINE_AUTHKEY" --server_url="$REDMINE_URL"
    echo ""
}

function redmine_help_with_current_user_id
{
    cat <<__EOF__
Please configure your redmine instance :
    git config --global --add redmine.user.id ID

__EOF__
    /usr/local/share/Weborama-Git-Review/helpers/redmine-get-current-user-id --auth_key="$REDMINE_AUTHKEY" --server_url="$REDMINE_URL"
    echo ""
}

if [ "x$REDMINE_AUTHKEY" == "x" ] || [ "x$REDMINE_URL" == "x" ]
then
    redmine_help
    exit 1
fi

export REDMINE_AUTHKEY REDMINE_URL

if [ "x$REDMINE_REVIEW_TODO" == "x" ] || [ "x$REDMINE_REVIEW_IN_PROGRESS" == "x" ] || [ "x$REDMINE_REVIEW_FINISH" == "x" ] || [ "x$REDMINE_TASK_TODO" == "x" ] || [ "x$REDMINE_TASK_IN_PROGRESS" == "x" ]
then
    redmine_help_with_statuses
    exit 1
fi

export REDMINE_REVIEW_TODO REDMINE_REVIEW_IN_PROGRESS REDMINE_REVIEW_FINISH REDMINE_TASK_TODO REDMINE_TASK_IN_PROGRESS

if [ "x$REDMINE_USER_ID" == "x" ]
then
    redmine_help_with_current_user_id
    exit 1
fi

export REDMINE_USER_ID

