#!/bin/bash

function redmine_set_status
{
	declare -a PARAMS

	PARAMS+=(--auth_key "$REDMINE_AUTHKEY")
	PARAMS+=(--server_url "$REDMINE_URL")
	PARAMS+=(--id "$task")
	PARAMS+=(--status_id "$status")
	PARAMS+=(--assigned_to_id "$assigned_to")

	declare -a ADD_PARAMS
	if [ "$status" = "$REDMINE_REVIEW_TODO" ]
		then
		ADD_PARAMS+=(--progress "100")
	elif [ -n "$progress" ]
		then
		ADD_PARAMS+=(--progress "$progress")
	fi

	if [ -n "$notes" ]
		then
		ADD_PARAMS+=(--notes "$notes")
	fi

	if [ -n "$git_repos_id" ] && [ -n "$git_repos_url" ]
		then
		ADD_PARAMS+=(--cf_id "$git_repos_id")
		ADD_PARAMS+=(--cf_val "$git_repos_url")
	elif [ -n "$git_pr_id" ] && [ -n "$git_pr_val" ]
		then
		ADD_PARAMS+=(--cf_id "$git_pr_id")
		ADD_PARAMS+=(--cf_val "$git_pr_val")
	fi


    /usr/local/share/Git-Redmine-Suite/helpers/redmine-set-status-id "${PARAMS[@]}" "${ADD_PARAMS[@]}"
    /usr/local/share/Git-Redmine-Suite/helpers/redmine-check-task "${PARAMS[@]}"
}

