#!/bin/bash

function redmine_projects_slug
{
    /usr/local/share/Git-Redmine-Suite/helpers/redmine-get-project-slug --auth_key="$REDMINE_AUTHKEY" --server_url="$REDMINE_URL"
    echo ""
}

function redmine_get_project
{
    /usr/local/share/Git-Redmine-Suite/helpers/redmine-get-project --id="$1" --auth_key="$REDMINE_AUTHKEY" --server_url="$REDMINE_URL" 2> /dev/null
    if [ $? -ne 0 ]
    then
        echo "Can't fetch the task $1. This task exist ? Your server is properly configurated ?" 1>&2
        exit 1
    fi
}

function redmine_get_all_active_projects
{
    git config --get-regexp ^redmine.project | cut -d "." -f 3 | sort -u
}

function redmine_get_project_users
{
    cat <<__EOF__
Please configure your project "$1" for task finish and review :

    git redmine project setup $1 TASK_FINISHED_USER_ID REVIEW_FINISHED_USER_ID RELEASE_FINISHED_USER_ID

__EOF__
    /usr/local/share/Git-Redmine-Suite/helpers/redmine-get-users-id --project="$1" --auth_key="$REDMINE_AUTHKEY" --server_url="$REDMINE_URL"
    echo ""
}
