#!/usr/bin/env perl
use feature 'say';
use strict;
use warnings;
{
    package MyOpts;
    use Moo;
    use MooX::Options;
    option 'id' => (
        is       => 'ro',
        required => 1,
        doc      => 'id of the task',
        format   => 'i',
    );
    option 'status_id' => (
        is => 'ro',
        required => 1,
        doc => 'id of the status',
        format => 'i',
    );
    option 'assigned_to_id' => (
        is => 'ro',
        required => 1,
        doc => 'id of user to assign to',
        format => 'i',
    );
    option 'notes' => (
        is => 'ro',
        doc => 'notes for your change',
        format => 's',
    );
    option 'auth_key' => (
        is => 'ro',
        format => 's',
        required => 1,
        doc => 'your auth key',
    );
    option 'server_url' => (
        is => 'ro',
        format => 's',
        required => 1,
        doc => 'the redmine url of the server',
    );
    option 'trace' => (
        is => 'ro',
        default => sub { 0 },
        doc => 'debug mode',
    );
    1;
};

my $opt = MyOpts->new_with_options;

use Redmine::API;
my $r = Redmine::API->new(
    'auth_key' => $opt->auth_key,
    'base_url' => $opt->server_url,
    'trace' => $opt->trace,
);

my $id = $opt->id;
my $status_id = $opt->status_id;
my $assigned_to_id = $opt->assigned_to_id;
my $notes = $opt->notes // '';
my $resp = $r->issues->issue->update($id, status_id => $status_id, assigned_to_id => $assigned_to_id, notes => $notes);

