#!/bin/bash

REDMINE_AUTHKEY=$(git config redmine.authkey)
REDMINE_URL=$(git config redmine.url)
REDMINE_REVIEW_TODO=$(git config redmine.statuses.review.todo)
REDMINE_REVIEW_IN_PROGRESS=$(git config redmine.statuses.review.inprogress)
REDMINE_REVIEW_FINISH=$(git config redmine.statuses.review.finish)
REDMINE_USER_ID=$(git config redmine.user.id)
REDMINE_PROJECT=$(git config redmine.project)

function redmine_help
{
    cat <<__EOF__
Please configure your redmine instance :
    git config --global --add redmine.authkey YOUR_AUTH_KEY
    git config --global --add redmine.url THE_REDMINE_URL_SERVER
    git config --global --add redmine.statuses.review.todo ID
    git config --global --add redmine.statuses.review.inprogress ID
    git config --global --add redmine.statuses.review.finish ID
    git config --global --add redmine.user.id ID
    git config --add redmine.project PROJECT_SLUG

__EOF__
}

function redmine_help_with_statuses
{
    redmine_help
    /usr/local/share/Weborama-Git-Review/helpers/redmine-get-statuses-ids --auth_key="$REDMINE_AUTHKEY" --server_url="$REDMINE_URL"
    echo ""
}

function redmine_help_with_current_user_id
{
    redmine_help
    /usr/local/share/Weborama-Git-Review/helpers/redmine-get-current-user-id --auth_key="$REDMINE_AUTHKEY" --server_url="$REDMINE_URL"
    echo ""
}

function redmine_help_with_project_slug
{
    redmine_help
    /usr/local/share/Weborama-Git-Review/helpers/redmine-get-project-slug --auth_key="$REDMINE_AUTHKEY" --server_url="$REDMINE_URL"
    echo ""
}

if [ "x$REDMINE_AUTHKEY" == "x" ] || [ "x$REDMINE_URL" == "x" ]
then
    redmine_help
    exit 1
fi

export REDMINE_AUTHKEY REDMINE_URL

if [ "x$REDMINE_REVIEW_TODO" == "x" ] || [ "x$REDMINE_REVIEW_IN_PROGRESS" == "x" ] || [ "x$REDMINE_REVIEW_FINISH" == "x" ]
then
    redmine_help_with_statuses
    exit 1
fi

export REDMINE_REVIEW_TODO REDMINE_REVIEW_IN_PROGRESS REDMINE_REVIEW_FINISH

if [ "x$REDMINE_USER_ID" == "x" ]
then
    redmine_help_with_current_user_id
fi

export REDMINE_USER_ID

if [ "x$REDMINE_PROJECT" == "x" ]
then
    redmine_help_with_project_slug
fi

export REDMINE_PROJECT
