#!/usr/bin/perl
use strict;
use warnings;
use feature 'say';
use DateTime;
{
    package MyOpt;
    use Moo;
    use MooX::Options;
    option 'version' => ( is => 'ro', format => 's', required => 1, doc => 'Version to tag');
    1;
}

my $opt = MyOpt->new_with_options;
my $d = DateTime->now(time_zone => 'UTC');
say $opt->version, "      ", $d->ymd('-'), " ", $d->hms(':'), " GMT";
say "";

