=head1 SETUP GUIDE

Welcome to the setup guide.

This guide lead you to :

 * understand the link between redmine and your git repositories
 * setup git redmine
 * manager redmine project in your git repository

=head1 EXPLANATION

Redmine is composed of projects. Each project can have multiple git repositories.

For example, you have project TEST with :

 * ORM
 * Collect
 * Compute
 * ...

Each git repository may have a different reviewers.

If you have a task in redmine that lead to change multiple git repositories, you have to create one subtask per git repository.

Each start/finish will update the task in redmine.

=head1 REDMINE GLOBAL AUTO SETUP

You can use a profile to setup your redmine.

This will setup all keys for you, in git config --global.

The command :

 * git redmine setup global

This will list you the profile available. Now only "weborama" and "celogeek" is present.

To complete the auto setup :

 * git redmine setup global weborama AUTH_KEY

The AUTH_KEY can be found in your account in redmine. Under "API access key", click on "Show", copy paste the key.

=head1 REDMINE LOCAL AUTO SETUP

You can also setup your auth key for one git project only.

It the same as "global", but with "local".

 * git redmine setup local weborama AUTH_KEY

=head1 REDMINE MANUEL SETUP

The best way to know what you have to do, is to run a command.

 * git redmine task pending

The first is to setup the "auth_key" and the "url" of the server :

 * git config --global redmine.authkey YOUR_AUTH_KEY
 * git config --global redmine.url THE_REDMINE_URL_SERVER

Warning, to use a "HTTPS" url in redmine you MUST have a VALID CERTIFICAT !

If you are looking for one, you can get one freely on L<https://www.startssl.com/>.

Then run the command again to file the next step :

 * git redmine task pending

You have to setup the ids of statuses. It will allow the tools to setup the status of the task properl :

 * git config --global redmine.statuses.task.assigned ID
 * => The ID of the status when a task is assigned to you.

 * git config --global redmine.statuses.task.inprogress ID
 * => The ID of the status when you are working on a task.

 * git config --global redmine.statuses.review.assigned ID
 * => The ID of the status when a task need a review by you.

 * git config --global redmine.statuses.review.inprogress ID
 * => The ID of the status when a task is currently review by you.

 * git config --global redmine.statuses.release.assigned ID
 * => The ID of the status when a task has to be released by you.

 * git config --global redmine.statuses.release.finish ID
 * => The ID of the status when a task has been released.

You can then run the command again :

 * git redmine task pending

You need to tell which ID is you. They is only one possibility. It will be display above.

 * git config --global redmine.user.id ID

The command should work now.

 * git redmine task pending

But display nothing. This is normal you have to setup project for that.

=head1 PROJECT SETUP

The project need 3 custom fields to be compatible with Git Redmine Suite : GIT_REPOS, GIT_PR, GIT_RELEASE.

The task management will use it to save meta information.

 * GIT_REPOS should be a text field with "Used as a filter" and "Searchable" checked.
 * GIT_PR should be a text.
 * GIT_RELEASE should be a text.

You can add them "For all project". Otherwise the search will be a little bit slower due to Redmine issue on that.

=head1 AUTHORS

 * Vincent Bachelier (vincent@weborama.com)
 * Celogeek (me@celogeek.com)

=cut

=head1 PRIORITY COLORS

You can personalize the priority color.

  git config --global redmine.priocolor "[PRIO_NAME]=[AINSI_COLOR_CODE]:[PRIO_NAME_2]=[AINSI_COLOR_CODE2]"

Example :

  git config --global redmine.priocolor "Immediate=1;41:Urgent=1;31:High=1;37:Normal=37:Low=34"

That means :

  Priority with name "Immediate" is background red bold white
  Priority with name "Urgent" is bold red
  Priority with name "High" is bold white
  Priority with name "Normal" is white
  Priority with name "Low" is blue

The name of priority is in "Administration section / Enumeration"

For the ainsi code, take a look here : L<http://pueblo.sourceforge.net/doc/manual/ansi_color_codes.html>

You need to take the number between the "[" and the "m".

Example :

	[1m - bold => take 1
	[31m - foreground red => take 31

You can combine multiple attribute :

	bold;foreground red;background white : 1;31;47