=head1 DEVELOPERS GUIDE

Welcome to the developers guide.

This guide lead you to :

 * manage your task

First of all, you have to follow the "setup guide" :

 * git redmine guide setup

=head1 Link a git project to redmine

First of all, when you get into a git repository, you need to link it to a redmine project`.

You can use "git redmine project" for this purpose. I suggest you to read the "setup" guide, to understand how it works.

=head1 What your jobs ?

When your redmine projects are linked, you can get the list of your "pending" task.

 * git redmine task pending

All tasks and their parent are shown. Pick one of then.

=head1 Start a task

To start a task, 

 * git redmine task start XXX

The XXX is the number of the task. It will create a branch locally and remotely. Your redmine will change from "assigned" to "in progress".

You can do multiple think with that.

=over

=item commit

You can commit as usual, then just push.

 * git push

It will push on the remote branch your current local development.

=item update from origin/devel

To update your local branch,

 * git fetch -ap
 * git fetch tags -p
 * git rebase origin/devel
 * git push -f

=back

=head1 AUTHORS

 * Vincent Bachelier (vincent@weborama.com)
 * Celogeek (me@celogeek.com)

=cut
