=head1 REVIEWERS GUIDE

Welcome to the REVIEWERS guide.

This guide lead you to :

 * review the tasks
 * merge into devel

First of all, you have to follow the "setup guide" :

 * git redmine guide setup

=head1 AUTHORS

 * Vincent Bachelier (vincent@weborama.com)
 * Celogeek (me@celogeek.com)

=cut
