#!/bin/bash

source /usr/local/share/Git-Redmine-Suite/helpers/current_git_command
if [ -n "$HELP" ]
then
    echo "$CURRENT_GIT_COMMAND"
    exit 1
fi

set -e

source /usr/local/share/Git-Redmine-Suite/helpers/redmine-checkconf
source /usr/local/share/Git-Redmine-Suite/helpers/redmine-project

GIT_REPOS_ID=$(git config --get-regexp ^redmine.project.*.git.repos | head -n1 | cut -d " " -f 2)
if [ -z "$GIT_REPOS_ID" ]
	then
	echo "You need to configure at least one project, to get the global GIT_REPOS value."
	exit 1
fi
GIT_REPOS_URL=$(git config remote.origin.url)

/usr/local/share/Git-Redmine-Suite/helpers/redmine-get-tasks --auth_key="$REDMINE_AUTHKEY" --server_url="$REDMINE_URL" --status_id="$REDMINE_REVIEW_TODO" --cf_id="$GIT_REPOS_ID" --cf_val="$GIT_REPOS_URL"