#!/bin/bash

source /usr/local/share/Git-Redmine-Suite/helpers/current_git_command
if [ -n "$HELP" ]
then
    echo "$CURRENT_GIT_COMMAND PROFILE AUTH_KEY"
    exit 1
fi

function common_setup
{
    git config --global alias.release "redmine release"
    git config --global alias.review "redmine review"
    git config --global alias.task "redmine task"
    git config --global alias.project "redmine project"
    git config --global push.default "tracking"
}

set -e
case $1 in
    weborama)
        echo "Setup profile weborama ..."
        REDMINE_URL="http://redmine.intranet.weborama.com"
        REDMINE_AUTHKEY="$2"
        if [ -z "$REDMINE_AUTHKEY" ]
        then
            echo "You need to pass your auth key from redmine to run the setup !"
            echo ""
            exit 1
        fi
        git config --global redmine.url "$REDMINE_URL"
        git config --global redmine.authkey "$REDMINE_AUTHKEY"
        git config --global redmine.user.id $(/usr/local/share/Git-Redmine-Suite/helpers/redmine-get-current-user-id --auth_key="$REDMINE_AUTHKEY" --server_url="$REDMINE_URL" --id_only)
        git config --global redmine.statuses.task.assigned 2
        git config --global redmine.statuses.task.inprogress 7
        git config --global redmine.statuses.review.assigned 14
        git config --global redmine.statuses.review.inprogress 27
        git config --global redmine.statuses.release.assigned 10
        git config --global redmine.statuses.release.finish 26
        common_setup
        echo ""
    ;;
    celogeek)
        echo "Setup profile celogeek ..."
        REDMINE_URL="https://tasks.celogeek.com"
        REDMINE_AUTHKEY="$2"
        if [ -z "$REDMINE_AUTHKEY" ]
        then
            echo "You need to pass your auth key from redmine to run the setup !"
            echo ""
            exit 1
        fi
        git config --global redmine.url "$REDMINE_URL"
        git config --global redmine.authkey "$REDMINE_AUTHKEY"
        git config --global redmine.user.id $(/usr/local/share/Git-Redmine-Suite/helpers/redmine-get-current-user-id --auth_key="$REDMINE_AUTHKEY" --server_url="$REDMINE_URL" --id_only)
        git config --global redmine.statuses.task.assigned 1
        git config --global redmine.statuses.task.inprogress 2
        git config --global redmine.statuses.review.assigned 3
        git config --global redmine.statuses.review.inprogress 4
        git config --global redmine.statuses.release.assigned 7
        git config --global redmine.statuses.release.finish 5
        common_setup
        echo ""
    ;;
    *)
        echo "$CURRENT_GIT_COMMAND PROFILE AUTH_KEY"
        echo ""
        echo "Profiles :"
        echo ""
        echo "    * celogeek"
        echo "    * weborama"
        echo ""
    ;;
esac
