#!/bin/bash

source /usr/local/share/Git-Redmine-Suite/helpers/current_git_command
if [ -n "$HELP" ]
then
    echo "$CURRENT_GIT_COMMAND PROJECT REVIEWER RELEASER INTEGRATOR"
    exit 1
fi

set -e

source /usr/local/share/Git-Redmine-Suite/helpers/redmine-checkconf
source /usr/local/share/Git-Redmine-Suite/helpers/redmine-project

PROJECT=$1
if [ -z "$PROJECT" ]
then
    echo "You have to give a project slug : "
    echo ""
    redmine_projects_slug
    exit 1
fi

redmine_get_project_cf $PROJECT

if [ -z $GIT_REPOS ] || [ -z $GIT_PR ] || [ -z $GIT_RELEASE ]
then
	echo "Invalid project. Please be sure that the project contain the custom fields GIT_REPOS, GIT_PR, GIT_RELEASE
"
	exit 1
fi

TASK=$2
REVIEW=$3
RELEASE=$4

if [ -z "$TASK" ] || [ -z "$REVIEW" ]
then
    redmine_get_project_users "$PROJECT"
    exit 1
fi

echo "Setup project $PROJECT with Reviewer: $TASK, Releaser: $REVIEW, Integrator: $RELEASE"
git config redmine.project.$PROJECT.finish.user.id.task $TASK
git config redmine.project.$PROJECT.finish.user.id.review $REVIEW
git config redmine.project.$PROJECT.finish.user.id.release $RELEASE
git config redmine.cf.git.repos $GIT_REPOS
git config redmine.cf.git.pr $GIT_PR
git config redmine.cf.git.release $GIT_RELEASE
echo ""

