#!/bin/bash

source /usr/local/share/Git-Redmine-Suite/helpers/current_git_command
if [ -n "$HELP" ]
then
    echo "$CURRENT_GIT_COMMAND"
    exit 1
fi

set -e

source /usr/local/share/Git-Redmine-Suite/helpers/redmine-checkconf
source /usr/local/share/Git-Redmine-Suite/helpers/redmine-project

/usr/local/share/Git-Redmine-Suite/helpers/redmine-get-tasks --auth_key="$REDMINE_AUTHKEY" --server_url="$REDMINE_URL" --assigned_to_id="$REDMINE_USER_ID" --status_id="$REDMINE_TASK_TODO"
