#!/bin/bash

source /usr/local/share/Git-Redmine-Suite/helpers/current_git_command
function help {
    echo "$CURRENT_GIT_COMMAND TASK_DEP_1 TASK_DEP_2 ..."
    exit 1
}

if [ -n "$HELP" ]
then
    help
fi

set -e

source /usr/local/share/Git-Redmine-Suite/helpers/redmine-checkconf
source /usr/local/share/Git-Redmine-Suite/helpers/redmine-question

set +e

TASK=$(git config redmine.task.current)

if [ -z "$TASK" ]
then
    echo "You have not start any task !"
    exit 1
fi

set -e

DEPS="$@"

if [ -z "$DEPS" ]
then
    help
fi

are_you_sure "Set deps for task $TASK to $DEPS ?"
git config redmine.task.${TASK}.depends "$DEPS"
