#!/bin/bash
function redmine_get_title
{
    declare -a PARAMS=(--id "$1" --auth_key "$REDMINE_AUTHKEY" --server_url "$REDMINE_URL")
    if [ -n "$status" ]
        then
        PARAMS+=(--with_status)
    fi
    if [ -n "$extended_status" ]
        then
        PARAMS+=(--with_extended_status)
    fi

    /usr/local/share/Git-Redmine-Suite/helpers/redmine-get-title ${PARAMS[@]} 2> /dev/null
    if [ $? -ne 0 ]
    then
        echo "Can't fetch the task $1. This task exist ? Your server is properly configurated ?" 1>&2
        exit 1
    fi
}
